tasks:
  - name: docker-compose 
    init: docker-compose create
    command: docker-compose up -d
  - name: npm install
    init: npm install
    command: npm run devgit
ports:
    - name: login
      port: 1025
      protocol: https

