tasks:
  - name: docker-compose 
    init: docker-compose create
    command: docker-compose up -d
  - name: npm install
    init: npm install
    command: npm run dev
    name: login
    port: 3000
    protocol: https
    onOpen: open-browser
