# simple docker-compose with a single postgres db

version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ../data:/var/lib/postgresql/data

  mailer:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025